<!-- ############################# Ajax Page Container ############################# -->
<section id="page" data-title="sounds.sg | terms of use">
    <section class="content section">
        <div class="container" style="width: 80%;">
            <article>
                <h1><span class="color">sounds.sg</span> Terms of Use</h1>
                <p>Welcome to <span class="color">sounds.sg</span>, a service provided by sounds.sg &reg; (&ldquo;<span class="color">sounds.sg</span>&rdquo;, &ldquo;<strong>we</strong>&rdquo; &ldquo;<strong>our</strong>&rdquo;, or &ldquo;<strong>us</strong>&rdquo;).</p>
                <p>These Terms of Use govern your use of <span class="color">sounds.sg</span> (together, the &ldquo;<strong>Website</strong>&rdquo;), our mobile and desktop apps (our "<strong>App</strong>s") and all related players, widgets, tools, applications, data, software, APIs (which may also be subject to separate API Terms of Use) and other services provided by <span class="color">sounds.sg</span> (the &ldquo;<strong>Services</strong>&rdquo;).</p>
                <p>These Terms of Use, together with our Privacy Policy, Cookies Policy, Community Guidelines and any other terms specifically referred to in any of those documents, constitute a legally binding agreement (the &ldquo;<strong>Agreement</strong>&rdquo;) between you and <span class="color">sounds.sg</span> in relation to your use of the Website, Apps and Services (together, the &ldquo;<strong>Platform</strong>&rdquo;).</p>
                <h2>Acceptance of Terms of Use</h2>
                <p>Please read these Terms of Use, our Privacy Policy and Cookies Policy very carefully. If you do not agree to any of the provisions set out in those documents, you should not use the Website, Apps or any of the Services. By accessing or using the Platform, registering an account, or by viewing, accessing, streaming, uploading or downloading any information or content from or to the Platform, you represent and warrant that you have read and understood the Terms of Use, Privacy Policy, and Cookies Policy, will abide by them, and that you are either 18 years of age or more, or you are 13 years of age or more and have your parent(s)&rsquo; or legal guardian(s)&rsquo; permission to use the Platform.</p>
                <h2>Changes to Terms of Use</h2>
                <p>We reserve the right to change, alter, replace or otherwise modify these Terms of Use at any time. The date of last modification is stated at the end of these Terms of Use. It is your responsibility to check this page from time to time for updates.</p>
                <p>When we make any updates to these Terms of Use, we will highlight this fact on the Website. In addition, if you register an account and these Terms of Use are subsequently changed in any material respect (for example, for security, legal, or regulatory reasons), we will notify you in advance by sending a message to your <span class="color">sounds.sg</span>&reg; account and/or an email to the email address that you have provided to us, and the revised Terms of Use will become effective six (6) weeks after such notification. You will have no obligation to continue using the Platform following any such notification, but if you do not terminate your account as described in the Termination section below during such six (6) week period, your continued use of the Platform after the end of that six (6) week period will constitute your acceptance of the revised Terms of Use.</p>
                <h2>Description of the Platform</h2>
                <p>The Platform is a hosting service. Registered users of the Platform may submit, upload and post audio, text, photos, pictures, graphics, and other content, data or information (&ldquo;<strong>Content</strong>&rdquo;), which will be stored by <span class="color">sounds.sg</span> at the direction of such registered users, and may be shared and distributed by such registered users, and other users of the Platform, using the tools and features provided as part of the Platform and accessible via the Website, Apps and elsewhere. The Platform&nbsp; enables any user of the Website, Apps or certain Services (who may or may not be registered users of the Platform) to view, listen to and share Content uploaded and made available by registered users.</p>
                <p>We may, from time to time, release new tools and resources on the Website, release new versions of our Apps, or introduce other services and/or features for the Platform. Any new services and features will be subject to these Terms of Use as well as any additional terms of use that we may release for those specific services or features.</p>
                <h2>Your <span class="color">sounds.sg</span> Account</h2>
                <p>You are not obliged to register to use the Platform. However, access to certain Services is only available to registered users.</p>
                <p>When you register to use the Platform, you will provide us with your email address, and will choose a username and password for your account. You must ensure that the email address that you provide is, and remains, valid. Your email address and any other information you chose to provide about yourself will be treated in accordance with our Privacy Policy.</p>
                <p>You are solely responsible for maintaining the confidentiality and security of your username and password, and you will remain responsible for all use of your username and password, and all activity emanating from your account, whether or not such activity was authorized by you.</p>
                <p>If your username or password is lost or stolen, or if you believe that your account has been accessed by unauthorized third parties, you are advised to notify <span class="color">sounds.sg</span> in writing, and should change your password at the earliest possible opportunity.</p>
                <p>We reserve the right to disallow, cancel, remove or reassign certain usernames and permalinks in appropriate circumstances, as determined by us in our sole discretion, and may, with or without prior notice, suspend or terminate your account if activities occur on that account which, in our sole discretion, would or might constitute a violation of these Terms of Use, or an infringement or violation of the rights of any third party, or of any applicable laws or regulations.</p>
                <p>You may terminate your account at any time as described in the Termination section below.</p>
                <h2>Your Use of the Platform</h2>
                <p>Subject to your strict compliance with these Terms of Use, <span class="color">sounds.sg</span> grants you a limited, personal, non-exclusive, revocable, non-assignable and non-transferable right and licence to use the Platform in order to view Content uploaded and posted to the Website, to listen to audio Content streamed from the Platform and to share and download audio Content using the features of the Platform where the appropriate functionality has been enabled by the user who uploaded the relevant Content (the &ldquo;<strong>Uploader</strong>&rdquo;).</p>
                <p>In addition, if you register to use the Platform, and subject to your strict compliance with these Terms of Use, <span class="color">sounds.sg</span> grants you a limited, personal, non-exclusive, revocable, non-assignable and non-transferable right and licence to:</p>
                <p>(i) submit, upload or post Content to the Platform strictly as permitted in accordance with these Terms of Use and any other applicable terms posted on the Website from time to time;</p>
                <p>(ii) use or Apps and other Services provided as part of the Platform strictly as permitted in accordance with these Terms of Use and any other terms applicable to those Apps or Services from time to time.</p>
                <p>The above licences are conditional upon your strict compliance with these Terms of Use, including, without limitation, the following:</p>
                <p>(i) You must not copy, rip or capture, or attempt to copy, rip or capture, any audio Content from the Platform or any part of the Platform, other than by means of download in circumstances where the relevant Uploader has elected to permit downloads of the relevant item of Content.</p>
                <p>(ii) You must not adapt, copy, republish, make available or otherwise communicate to the public, display, perform, transfer, share, distribute or otherwise use or exploit any Content on or from the Platform, except (i) where such Content is Your Content, or (ii) as permitted under these Terms of Use, and within the parameters set by the Uploader.</p>
                <p>(iii) You must not use any Content (other than Your Content) in any way that is designed to create a separate content service or that replicates any part of the Platform offering.</p>
                <p>(iv) You must not employ scraping or similar techniques to aggregate, repurpose, republish or otherwise make use of any Content.</p>
                <p>(v) You must not employ any techniques or make use of any services, automated or otherwise, designed to misrepresent the popularity of Your Content on the Platform, or to misrepresent your activity on the Platform, including without limitation by the use of bots, botnets, scripts, apps, plugins, extensions or other automated means to register accounts, log in, add followers to your account, play Content, or otherwise to act on your behalf, particularly where such activity occurs in a multiple or repetitive fashion. You must not offer or promote the availability of any such techniques or services to any other users of the Platform.</p>
                <p>(vi) You must not alter or remove, attempt to alter or remove, any trademark, copyright or other proprietary or legal notices contained in, or appearing on, the Platform or any Content appearing on the Platform (other than Your Content).</p>
                <p>(vii) You must not, and must not permit any third party to, copy or adapt the object code of the Website or any of the Apps or Services, or reverse engineer, reverse assemble, decompile, modify or attempt to discover any source or object code of any part of the Platform, or circumvent or attempt to circumvent or copy any copy protection mechanism or access any rights management information pertaining to Content other than Your Content.</p>
                <p>(viii) You must not use the Platform to upload, post, store, transmit, display, copy, distribute, promote, make available or otherwise communicate to the public:</p>
                <ul>
                    <li>any Content that is offensive, abusive, libellous, defamatory, obscene, racist, sexually explicit, ethnically or culturally offensive, indecent, that promotes violence, terrorism, or illegal acts, incites hatred on grounds of race, gender, religion or sexual orientation, or is otherwise objectionable in sg&rsquo;s reasonable discretion;</li>
                    <li>any information, Content or other material that violates, plagiarises, misappropriates or infringes the rights of third parties including, without limitation, copyright, trademark rights, rights of privacy or publicity, confidential information or any other right; or</li>
                    <li>any Content that violates, breaches or is contrary to any law, rule, regulation, court order or is otherwise is illegal or unlawful in sg&rsquo;s reasonable opinion;</li>
                    <li>any material of any kind that contains any virus, Trojan horse, spyware, adware, malware, bot, time bomb, worm, or other harmful or malicious component, which or might overburden, impair or disrupt the Platform or servers or networks forming part of, or connected to, the Platform, or which does or might restrict or inhibit any other user's use and enjoyment of the Platform; or</li>
                    <li>any unsolicited or unauthorised advertising, promotional messages, spam or any other form of solicitation.</li>
                </ul>
                <p>(ix) You must not commit or engage in, or encourage, induce, solicit or promote, any conduct that would constitute a criminal offence, give rise to civil liability or otherwise violate any law or regulation.</p>
                <p>(x) You must not rent, sell or lease access to the Platform, or any Content on the Platform, although this shall not prevent you from including links from Your Content to any legitimate online download store from where any item of Your Content may be purchased.</p>
                <p>(xi) You must not deliberately impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity, for example, by registering an account in the name of another person or company.</p>
                <p>(xii) You must not stalk, exploit, threaten, abuse or otherwise harass another user, or any <span class="color">sounds.sg</span> employee.</p>
                <p>(xiii) You must not use or attempt to use another person's account, password, or other information, unless you have express permission from that other person.</p>
                <p>(xiv) You must not sell or transfer, or offer to sell or transfer, any <span class="color">sounds.sg</span> account to any third party without the prior written approval of <span class="color">sounds.sg</span>.</p>
                <p>(xv) You must not collect or attempt to collect personal data, or any other kind of information about other users, including without limitation, through spidering or any form of scraping.</p>
                <p>(xvi) You must not violate, circumvent or attempt to violate or circumvent any data security measures employed by <span class="color">sounds.sg</span> or any Uploader; access or attempt to access data or materials which are not intended for your use; log into, or attempt to log into, a server or account which you are not authorized to access; attempt to scan or test the vulnerability of <span class="color">sounds.sg</span>&rsquo;s servers, system or network or attempt to breach <span class="color">sounds.sg</span>&rsquo;s data security or authentication procedures; attempt to interfere with the Website or the Services by any means including, without limitation, hacking <span class="color">sounds.sg</span>&rsquo;s servers or systems, submitting a virus, overloading, mail-bombing or crashing. Without limitation to any other rights or remedies of <span class="color">sounds.sg</span> under these Terms of Use, <span class="color">sounds.sg</span> reserves the right to investigate any situation that appears to involve any of the above, and may report such matters to, and co-operate with, appropriate law enforcement authorities in prosecuting any users who have participated in any such violations.</p>
                <p>You agree to comply with the above conditions, and acknowledge and agree that <span class="color">sounds.sg</span> has the right, in its sole discretion, to terminate your account or take such other action as we see fit if you breach any of the above conditions or any of the other terms of these Terms of Use. This may include taking court action and/or reporting offending users to the relevant authorities.</p>
                <h2>Your Content</h2>
                <p>Any and all audio, text, photos, pictures, graphics, comments, and other content, data or information that you upload, store, transmit, submit, exchange or make available to or via the Platform (hereinafter "Your Content") is generated, owned and controlled solely by you, and not by <span class="color">sounds.sg</span>.</p>
                <p><span class="color">sounds.sg</span> does not claim any ownership rights in Your Content, and you hereby expressly acknowledge and agree that Your Content remains your sole responsibility.</p>
                <p>Without prejudice to the conditions set forth in Your Use of the Platform you must not upload, store, distribute, send, transmit, display, perform, make available or otherwise communicate to the public any Content to which you do not hold the necessary rights. In particular, any unauthorized use of copyright protected material within Your Content (including by way of reproduction, distribution, modification, adaptation, public display, public performance, preparation of derivative works, making available or otherwise communicating to the public via the Platform) may constitute an infringement of third party rights and is <em>strictly prohibited</em>. Any such infringements may result in termination of your access to the Platform as described in the Repeat Infringers section below, and may also result in civil litigation or criminal prosecution by or on behalf of the relevant rightsholder.</p>
                <p>We may, from time to time, invite or provide you with means to provide feedback regarding the Platform, and in such circumstances, any feedback you provide will be deemed non-confidential and <span class="color">sounds.sg</span> shall have the right, but not the obligation, to use such feedback on an unrestricted basis.</p>
                <h2>Grant of Licence</h2>
                <p>By uploading or posting Your Content to the Platform, you initiate an automated process to transcode any audio Content and direct <span class="color">sounds.sg</span> to store Your Content on our servers, from where you may control and authorise the use, reproduction, transmission, distribution, public display, public performance, making available and other communication to the public of Your Content on the Platform and elsewhere using the Services. To the extent it is necessary in order for <span class="color">sounds.sg</span> to provide you with any of the aforementioned hosting services, to undertake any of the tasks set forth in these Terms of Use and/or to enable your use of the Platform, you hereby grant such licences to <span class="color">sounds.sg</span> on a limited, worldwide, non-exclusive, royalty-free and fully paid basis.</p>
                <p>By uploading Your Content to the Platform, you also grant a limited, worldwide, non-exclusive, royalty-free, fully paid up, licence to other users of the Platform, and to operators and users of any other websites, apps and/or platforms to which Your Content has been shared or embedded using the Services (&ldquo;<strong>Linked Services</strong>&rdquo;), to use, copy, repost, transmit or otherwise distribute, publicly display, publicly perform, adapt, prepare derivative works of, compile, make available and otherwise communicate to the public, Your Content utilising the features of the Platform from time to time, and within the parameters set by you using the Services. You can limit and restrict the availability of certain of Your Content to other users of the Platform, and to users of Linked Services, at any time using the settings on the sound page for each sound you upload, subject to the provisions of the Disclaimer section below. Notwithstanding the foregoing, nothing in these Terms of Use grants any rights to any other user of the Platform with respect to any proprietary name, logo, trademark or service mark uploaded by you as part of Your Content (for example, your profile picture) (&ldquo;<strong>Marks</strong>&rdquo;), other than the right to reproduce, publicly display, make available and otherwise communicate to the public those Marks, automatically and without alteration, as part of the act of reposting sounds with which you have associated those Marks.</p>
                <p>The licences granted in this section are granted separately with respect to each item of Your Content that you upload to the Platform. Licences with respect to audio Content, and any images or text within your account, will (subject to the following paragraph of these Terms of Use) terminate automatically when you remove such Content from your account. Licences with respect to comments or other contributions that you make on the Platform will be perpetual and irrevocable, and will continue notwithstanding any termination of your account.</p>
                <p>Removal of audio Content from your account will automatically result in the deletion of the relevant files from <span class="color">sounds.sg</span>&rsquo;s systems and servers. However, notwithstanding the foregoing, you hereby acknowledge and agree that once Your Content is distributed to a Linked Service, <span class="color">sounds.sg</span> is not obligated to ensure the deletion of Your Content from any servers or systems operated by the operators of any Linked Service, or to require that any user of the Platform or any Linked Service deletes any item of Your Content.</p>
                <p>Any Content other than Your Content is the property of the relevant Uploader, and is or may be subject to copyright, trademark rights or other intellectual property or proprietary rights. Such Content may not be reproduced, distributed, transmitted, re-uploaded, republished, displayed, sold, licensed, made available or otherwise communicated to the public or exploited for any purposes except via the features of the Platform from time to time and within the parameters set by the Uploader on the Platform or with the express written consent of the Uploader.</p>
                <h2>Representations and Warranties</h2>
                <p>You hereby represent and warrant to <span class="color">sounds.sg</span> as follows:</p>
                <p>(i) Your Content, and each and every part thereof, is an original work by you, or you have obtained all rights, licences, consents and permissions necessary in order to use, and (if and where relevant) to authorise <span class="color">sounds.sg</span> to use, Your Content pursuant to these Terms of Use, including, without limitation, the right to upload, reproduce, store, transmit, distribute, share, publicly display, publicly perform, make available and otherwise communicate to the public Your Content, and each and every part thereof, on, through or via the Website, any and all Services and any Linked Services.</p>
                <p>(ii) Your Content and the availability thereof on the Platform does not and will not infringe or violate the rights of any third party, including, without limitation, any intellectual property rights, performers&rsquo; rights, rights of privacy or publicity, or rights in confidential information.</p>
                <p>(iii) You have obtained any and all necessary consents, permissions and/or releases from any and all persons appearing in Your Content in order to include their name, voice, performance or likeness in Your Content and to publish the same on the Platform and via any Linked Services.</p>
                <p>(iv) Your Content, including any comments that you may post on the Website, is not and will not be unlawful, offensive, abusive, libellous, defamatory, obscene, racist, sexually explicit, ethnically or culturally offensive, indecent, will not promote violence, terrorism, or illegal acts, or incite hatred on grounds of race, gender, religion or sexual orientation.</p>
                <p>(v) Your Content does not and will not create any liability on the part of <span class="color">sounds.sg</span>, its subsidiaries, affiliates, successors, and assigns, and their respective employees, agents, directors, officers and/or shareholders.</p>
                <p><span class="color">sounds.sg</span> reserves the right to remove Your Content, suspend or terminate your access to the Platform and/or pursue all legal remedies if we believe that any of Your Content breaches any of the foregoing representations or warranties, or otherwise infringes another person's rights or violates any law, rule or regulation.</p>
                <h2>Liability for Content</h2>
                <p>You hereby acknowledge and agree that <span class="color">sounds.sg</span> (i) stores Content and other information at the direction, request and with the authorisation of its users, (ii) acts merely as a passive conduit and/or host for the uploading, storage and distribution of such Content, and (iii) plays no active role and gives no assistance in the presentation or use of the Content. You are solely responsible for all of Your Content that you upload, post or distribute to, on or through the Platform, and to the extent permissible by law, <span class="color">sounds.sg</span> excludes all liability with respect to all Content (including Your Content) and the activities of its users with respect thereto.</p>
                <p>You hereby acknowledge and agree that <span class="color">sounds.sg</span> does not have any obligation, nor assume any duty, to monitor the Platform for Content that is inappropriate, that does or might infringe any third party rights, or has otherwise been uploaded in breach of these Terms of Use or applicable law.</p>
                <p><span class="color">sounds.sg</span> hereby excludes, to the fullest extent permitted by law, any and all liability which may arise from any Content uploaded to the Platform by users, including, but not limited to, any claims for infringement of intellectual property rights, rights of privacy or publicity rights, any claims relating to publication of defamatory, pornographic, obscene or offensive material, or any claims relating to the completeness, accuracy, currency or reliability of any information provided by users of the Platform. By using the Platform, you irrevocably waive the right to assert any claim with respect to any of the foregoing against <span class="color">sounds.sg</span>.</p>
                <h2>Reporting Infringements</h2>
                <p>If you discover any Content on the Platform that you believe infringes your copyright, please report this to us using any of the methods outlined on our Copyright Information pages.</p>
                <p>If you would prefer to send us your own written notification, please make sure that you include the following information:</p>
                <ul>
                    <li>a statement that you have identified Content on sg&reg; that infringes your copyright or the copyright of a third party on whose behalf you are entitled to act;</li>
                    <li>a description of the copyright work(s) that you claim have been infringed;</li>
                    <li>a description of the Content that you claim is infringing and the sg URL(s) where such Content can be located;</li>
                    <li>your full name, address and telephone number, a valid email address on which you can be contacted, and your sg&reg; user name if you have one;</li>
                    <li>a statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright owner, its agent, or the law; and</li>
                    <li>a statement by you that the information in your notice is accurate and that you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed;</li>
                </ul>
                <p>Your notice should be sent to us by email to admin@<span class="color">sounds.sg</span></p>
                <p>In all other cases, if you discover Content that infringes any or violates any of your other rights, which you believe is defamatory, pornographic, obscene, racist or otherwise liable to cause widespread offence, or which constitutes impersonation, harassment, spam or otherwise violates these Terms of Use, our Community Guidelines or applicable law, please report this to us at admin@sound.sg.</p>
                <h2>Third Party Websites and Services</h2>
                <p>The Platform may provide you with access to third party websites, databases, networks, servers, information, software, programs, systems, directories, applications, products or services, including without limitation, Linked Services (hereinafter &ldquo;<strong>External Services</strong>&rdquo;).</p>
                <p><span class="color">sounds.sg</span> does not have or maintain any control over External Services, and is not and cannot be responsible for their content, operation or use. By linking or otherwise providing access to any External Services, <span class="color">sounds.sg</span> does not give any representation, warranty or endorsement, express or implied, with respect to the legality, accuracy, quality or authenticity of content, information or services provided by such External Services.</p>
                <p>External Services may have their own terms of use and/or privacy policy, and may have different practices and requirements to those operated by <span class="color">sounds.sg</span> with respect to the Platform. You are solely responsible for reviewing any terms of use, privacy policy or other terms governing your use of these External Services, which you use at your own risk. You are advised to make reasonable enquiries and investigations before entering into any transaction, financial or otherwise, and whether online or offline, with any third party related to any External Services.</p>
                <p>You are solely responsible for taking the precautions necessary to protect yourself from fraud when using External Services, and to protect your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content and material that may be included on or may emanate from any External Services.</p>
                <p><span class="color">sounds.sg</span> disclaims any and all responsibility or liability for any harm resulting from your use of External Services, and you hereby irrevocably waive any claim against <span class="color">sounds.sg</span> with respect to the content or operation of any External Services.</p>
                <h2>Blocking and Removal of Content</h2>
                <p>Notwithstanding the fact that <span class="color">sounds.sg</span> has no legal obligation to monitor the Content on the Platform, <span class="color">sounds.sg</span> reserves the right to block, remove or delete any Content at any time, and to limit or restrict access to any Content, for any reason and without liability, including without limitation, if we have reason to believe that such Content does or might infringe the rights of any third party, has been uploaded or posted in breach of these Terms of Use, our Community Guidelines or applicable law, or is otherwise unacceptable to <span class="color">sounds.sg</span>.</p>
                <p>Please also note that individual Uploaders have control over the audio Content that they store in their account from time to time, and may remove any or all audio Content or other Content without notice. You have no right of continued access to any particular item of Content and <span class="color">sounds.sg</span> shall have no liability in the event that you are unable to access an item of Content due to its removal from the Platform, whether by <span class="color">sounds.sg</span> or the relevant Uploader.</p>
                <h2>Repeat Infringers</h2>
                <p><span class="color">sounds.sg</span> will suspend or terminate your access to the Platform if <span class="color">sounds.sg</span> determines, in its reasonable discretion, that you have repeatedly breached these Terms of Use or our Community Guidelines.</p>
                <p>If we receive a valid notification from a third party in accordance with our reporting processes or applicable law that any of Your Content infringes the copyright or other rights of such third party, or if we believe that your behaviour is inappropriate and violates our Community Guidelines, we will send you a written warning to this effect. Any user that receives more than two of these warnings is liable to have their access to the Platform terminated forthwith.</p>
                <p>We will also suspend or terminate your account without warning if ordered to do so by a court, and/or in other appropriate circumstances, as determined by <span class="color">sounds.sg</span> at its discretion.</p>
                <h2>Disclaimer</h2>
                <p>THE PLATFORM, INCLUDING, WITHOUT LIMITATION, THE WEBSITE, THE APPS AND ALL CONTENT AND SERVICES ACCESSED THROUGH OR VIA THE WEBSITE, THE APPS OR OTHERWISE, ARE PROVIDED &ldquo;<strong>AS IS</strong>&rdquo;, &ldquo;<strong>AS AVAILABLE</strong>&rdquo;, AND &ldquo;<strong>WITH ALL FAULTS</strong>&rdquo;.</p>
                <p>WHILST SOUNDS.SG USES REASONABLE ENDEAVOURS TO CORRECT ANY ERRORS OR OMISSIONS IN THE PLATFORM AS SOON AS PRACTICABLE ONCE THEY HAVE BEEN BROUGHT TO SOUNDS.SG&rsquo;S ATTENTION, SOUNDS.SG MAKES NO PROMISES, GUARANTEES, REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER (EXPRESS OR IMPLIED) REGARDING THE WEBSITE, THE APPS, THE SERVICES OR ANY PART OR PARTS THEREOF, ANY CONTENT, OR ANY LINKED SERVICES OR OTHER EXTERNAL SERVICES. SOUNDS.SG DOES NOT WARRANT THAT YOUR USE OF THE PLATFORM WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE PLATFORM OR ANY PART OR PARTS THEREOF, THE CONTENT, OR THE SERVERS ON WHICH THE PLATFORM OPERATES ARE OR WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SOUNDS.SG DOES NOT WARRANT THAT ANY TRANSMISSION OF CONTENT UPLOADED TO THE PLATFORM WILL BE SECURE OR THAT ANY ELEMENTS OF THE PLATFORM DESIGNED TO PREVENT UNAUTHORISED ACCESS, SHARING OR DOWNLOAD OF CONTENT WILL BE EFFECTIVE IN ANY AND ALL CASES, AND DOES NOT WARRANT THAT YOUR USE OF THE PLATFORM IS LAWFUL IN ANY PARTICULAR JURISDICTION.</p>
                <p>SOUNDS.SG SPECIFICALLY DISCLAIMS ALL OF THE FOREGOING WARRANTIES AND ANY OTHER WARRANTIES NOT EXPRESSLY SET OUT HEREIN TO THE FULLEST EXTENT PERMITTED BY LAW, INCLUDING WITHOUT LIMITATION ANY EXPRESS OR IMPLIED WARRANTIES REGARDING NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</p>
                <p>WHERE THE LAW OF ANY JURISDICTION LIMITS OR PROHIBITS THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES AS SET OUT ABOVE, THE ABOVE DISCLAIMERS SHALL NOT APPLY TO THE EXTENT THAT THE LAW OF SUCH JURISDICTION APPLIES TO THIS AGREEMENT.</p>
                <h2>Limitation of Liability</h2>
                <p>SOUNDS.SG SHALL HAVE NO LIABILITY FOR:</p>
                <ol>
                    <li>ANY LOSS OR DAMAGE ARISING FROM:</li>
                </ol>
                <p>(A) YOUR INABILITY TO ACCESS OR USE THE PLATFORM OR ANY PART OR PARTS THEREOF, OR TO ACCESS ANY CONTENT OR ANY EXTERNAL SERVICES VIA THE PLATFORM;</p>
                <p>(B) ANY CHANGES THAT SOUNDS.SG MAY MAKE TO THE PLATFORM OR ANY PART THEREOF, OR ANY TEMPORARY OR PERMANENT SUSPENSION OR CESSATION OF ACCESS TO THE PLATFORM OR ANY CONTENT IN OR FROM ANY OR ALL TERRITORIES;</p>
                <p>(C) ANY ACTION TAKEN AGAINST YOU BY THIRD PARTY RIGHTSHOLDERS WITH RESPECT TO ANY ALLEGED INFRINGEMENT OF SUCH THIRD PARTY&rsquo;S RIGHTS RELATING TO YOUR CONTENT OR YOUR USE OF THE PLATFORM, OR ANY ACTION TAKEN AS PART OF AN INVESTIGATION BY SOUNDS.SG OR ANY RELEVANT LAW ENFORCEMENT AUTHORITY REGARDING YOUR USE OF THE PLATFORM;</p>
                <p>(D) ANY ERRORS OR OMISSIONS IN THE PLATFORM&rsquo;S TECHNICAL OPERATION, OR FROM ANY INACCURACY OR DEFECT IN ANY CONTENT OR ANY INFORMATION RELATING TO CONTENT;</p>
                <p>(E) YOUR FAILURE TO PROVIDE SOUNDS.SG WITH ACCURATE OR COMPLETE INFORMATION, OR YOUR FAILURE TO KEEP YOUR USERNAME OR PASSWORD SUITABLY CONFIDENTIAL;</p>
                <ol start="2">
                    <li>ANY LOSS OR DAMAGE TO ANY COMPUTER HARDWARE OR SOFTWARE, ANY LOSS OF DATA (INCLUDING YOUR CONTENT), OR ANY LOSS OR DAMAGE FROM ANY SECURITY BREACH; AND/OR</li>
                    <li>ANY LOSS OF PROFITS, OR ANY LOSS YOU SUFFER WHICH IS NOT A FORESEEABLE CONSEQUENCE OF SG BREACHING THESE TERMS OF USE. LOSSES ARE FORESEEABLE WHERE THEY COULD BE CONTEMPLATED BY YOU AND SOUNDS.SG AT THE TIME YOU AGREE TO THESE TERMS OF USE, AND THEREFORE DO NOT INCLUDE ANY INDIRECT LOSSES, SUCH AS LOSS OF OPPORTUNITY.</li>
                </ol>
                <p>ANY CLAIM OR CAUSE OF ACTION ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM MUST BE NOTIFIED TO SOUNDS.SG AS SOON AS POSSIBLE.</p>
                <p>APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH CASES, YOU ACKNOWLEDGE AND AGREE THAT SUCH LIMITATIONS AND EXCLUSIONS REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND SOUNDS.SG AND ARE FUNDAMENTAL ELEMENTS OF THE BARGAIN BETWEEN YOU AND SOUNDS.SG, AND THAT SOUNDS.SG&rsquo;S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
                <p>NOTHING IN THESE TERMS OF USE LIMITS OR EXCLUDES THE LIABILITY OF SOUNDS.SG, ITS SUBSIDIARIES, SUCCESSORS, ASSIGNS, OR THEIR RESPECTIVE EMPLOYEES, AGENTS, DIRECTORS, OFFICERS AND/OR SHAREHOLDERS: (I) FOR ANY DEATH OR PERSONAL INJURY CAUSED BY ITS OR THEIR NEGLIGENCE, (II) FOR ANY FORM OF FRAUD OR DECEIT, (III) FOR ANY DAMAGES CAUSED WILFULLY OR BY GROSS NEGLIGENCE, OR (IV) FOR ANY FORM OF LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY LAW.</p>
                <h2>Indemnification</h2>
                <p>You hereby agree to indemnify, defend and hold harmless <span class="color">sounds.sg</span> from and against any and all claims, obligations, damages, losses, expenses, and costs, including reasonable attorneys' fees, resulting from:</p>
                <p>(i) any violation by you of these Terms of Use or our Community Guidelines;</p>
                <p>(ii) any third party claim of infringement of copyright or other intellectual property rights or invasion of privacy arising from the hosting of Your Content on the Platform, and/or your making available thereof to other users of the Platform, and/or the actual use of Your Content by other users of the Platform or Linked Services in accordance with these Terms of Use and the parameters set by you with respect to the distribution and sharing of Your Content;</p>
                <p>(iii) any activity related to your account, be it by you or by any other person accessing your account with or without your consent unless such activity was caused by the act or default of <span class="color">sounds.sg</span>.</p>
                <h2>Data Protection, Privacy and Cookies</h2>
                <p>All personal data that you provide to us in connection with your use of the Platform is collected, stored, used and disclosed by <span class="color">sounds.sg</span> in accordance with our Privacy Policy. In addition, in common with most online services, we use cookies to help us understand how people are using the Platform, so that we can continue to improve the service we offer. Our use of cookies, and how to disable cookies, is explained in our Cookies Policy. By accepting these Terms of Use and using the Platform, you also accept the terms of the Privacy Policy and our Cookies Policy.</p>
                <h2>Meetups</h2>
                <p><span class="color">sounds.sg</span> has an active community of users, many of whom organize and attend face-to-face meetings at venues all over the world (&ldquo;<strong>Meetups</strong>&rdquo;). While <span class="color">sounds.sg</span> is generally supportive of Meetups and may provide branded promotional materials to help organisers promote their Meetups, <span class="color">sounds.sg</span> does not sponsor, oversee or in any way control such Meetups. You hereby acknowledge and agree that your attendance and participation in any Meetups is entirely at your own risk and <span class="color">sounds.sg</span> does not bear any responsibility or liability for the actions of any <span class="color">sounds.sg</span> users or any third parties who organize, attend or are otherwise involved in any Meetups.</p>
                <h2>Changes to the Platform</h2>
                <p><span class="color">sounds.sg</span> reserves the right at any time and for any reason to suspend, discontinue, terminate or cease providing access to the Platform or any part thereof, temporarily or permanently, and whether in its entirety or with respect to individual territories only. In the case of any temporary or permanent suspension, discontinuation, termination or cessation of access, <span class="color">sounds.sg</span> shall use its reasonable endeavours to notify registered users of such decision in advance.</p>
                <p>You hereby agree that <span class="color">sounds.sg</span> shall not be liable to you or to any third party for any changes or modifications to the Website, Apps and/or any Services that <span class="color">sounds.sg</span> may wish to make from time to time, or for any decision to suspend, discontinue or terminate the Website, the Services or any part or parts thereof, or your possibility to use or access the same from or within any territory or territories.</p>
                <p><span class="color">sounds.sg</span> may change the features of any type of account, may withdraw or, or introduce new features, products or types of account at any time and for any reason. In all other cases, where <span class="color">sounds.sg</span> proposes to make changes to any type of account to which you subscribe, and these changes are material and to your disadvantage, <span class="color">sounds.sg</span> will notify you of the proposed changes by sending a message to your <span class="color">sounds.sg</span>&reg; account and/or an email to the then current email address that we have for your account, at least six (6) weeks in advance. You will have no obligation to continue using the Platform following any such notification, but if you do not terminate your account as described in the Termination section below during such six (6) week period, your continued use of your account after the end of that six (6) week period will constitute your acceptance of the changes to your account.</p>
                <h2>Termination</h2>
                <p>You may terminate this Agreement at any time by sending notice in writing to <span class="color">sounds.sg</span> at admin@<span class="color">sounds.sg</span> confirming such termination, by removing all of Your Content from your account, by deleting your account and thereafter by ceasing to use the Platform.</p>
                <p><span class="color">sounds.sg</span> may suspend your access to the Platform and/or terminate this Agreement at any time if (i) you are deemed to be a Repeat Infringer as described above; (ii) you are in breach of any of the material provision of these Terms of Use or our Community Guidelines, including without limitation, the provisions of the following sections: Your Use of the Platform, Your Content, Grant of Licence , and Your Representations and Warranties; (iii) <span class="color">sounds.sg</span> elects at its discretion to cease providing access to the Platform in the jurisdiction where you reside or from where you are attempting to access the Platform, or (iv) in other reasonable circumstances as determined by <span class="color">sounds.sg</span> at its discretion.</p>
                <p>Once your account has been terminated, any and all Content residing in your account, or pertaining to activity from your account (for example, data relating to the distribution or consumption of your sounds), will be irretrievably deleted by <span class="color">sounds.sg</span>, except to the extent that we are obliged or permitted to retain such content, data or information for a certain period of time in accordance with applicable laws and regulations and/or to protect our legitimate business interests. You are advised to save or back up any material that you have uploaded to your account before terminating your account, as <span class="color">sounds.sg</span> assumes no liability for any material that is irretrievably deleted following any termination of your account.</p>
                <p>If you access the Platform via any of our Apps or via any third party app connected to your account, deleting that app will not delete your account. If you wish to delete your account, you will need to do so from the Account page within your Settings on the Website.</p>
                <p>The provisions of these Terms of Use that are intended by their nature to survive the termination or cancellation of this Agreement will survive the termination of this Agreement, including, but not limited to, those Sections entitled Your <span class="color">sounds.sg</span> Account, Your Content, Grant of Licence , Representations and Warranties, Liability for Content, Disclaimer, Limitation of Liability, Indemnification, Termination and Right of Cancellation, Assignment to Third Parties, Severability, Entire Agreement, and Applicable Law and Jurisdiction, respectively.</p>
                <h2>Assignment to Third Parties</h2>
                <p><span class="color">sounds.sg</span> may assign its rights and (where permissible by law) its obligations under this Agreement, in whole or in part, to any third party at any time without notice, including without limitation, to any person or entity acquiring all or substantially all of the assets or business of <span class="color">sounds.sg</span>. You may not assign this Agreement or the rights and duties hereunder, in whole or in part, to any third party without the prior written consent of <span class="color">sounds.sg</span>.</p>
                <h2>Severability</h2>
                <p>Should one or more provisions of these Terms of Use be found to be unlawful, void or unenforceable, such provision(s) shall be deemed severable and will not affect the validity and/or enforceability of the remaining provisions of the Terms of Use, which will remain in full force and effect.</p>
                <h2>Entire Agreement</h2>
                <p>These Terms of Use, together with the Community Guidelines, Privacy Policy and Cookies Policy, constitute the entire agreement between you and <span class="color">sounds.sg</span> with respect to your use of the Platform (other than any use of <span class="color">sounds.sg</span>&rsquo;s APIs which may also be subject to separate API Terms of Use), and supersede any prior agreement between you and <span class="color">sounds.sg</span>. Any modifications to this Agreement must be made in writing.</p>
                <h2>Third Party Rights</h2>
                <p>These Terms of Use are not intended to give rights to anyone except you and <span class="color">sounds.sg</span>. This does not affect our right to transfer our rights or obligations to a third party as described in the Assignment to Third Parties section.</p>
                <p>Last Amended: 17 December 2015</p>
            </article>
        </div>
    </section>
</section>
<!-- /page -->
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-66150326-1']);
    var d = document.location.pathname + document.location.search + document.location.hash;
    _gaq.push(['_trackPageview', d]);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
</script>